import { CDP, sleep } from './CDP.mjs';
import { writeFileSync } from 'fs';
const tab = [...(await (await fetch('http://127.0.0.1:9224/json/list')).json())].find(t => t.type === 'page' && /patch\.com/.test(t.url));
const ws = new WebSocket(tab.webSocketDebuggerUrl);
await new Promise((res, rej) => { ws.onopen = res; ws.onerror = rej; });
const c = new CDP(ws);
await c.send('Page.enable'); await c.send('Network.enable');
const reqs = [];
c.on(m => { if (m.method === 'Network.requestWillBeSent' && m.params.request.method === 'POST' && !/google|facebook|intercom|doubleclick|patch\.com\/cdn/.test(m.params.request.url)) reqs.push('POST ' + m.params.request.url.slice(0,110)); });
const ev = (t, p) => c.send('Input.dispatchMouseEvent', { type: t, ...p });
await ev('mouseMoved',{x:682,y:407}); await sleep(150);
await ev('mousePressed',{x:682,y:407,button:'left',clickCount:1}); await sleep(100);
await ev('mouseReleased',{x:682,y:407,button:'left',clickCount:1}); await sleep(400);
await c.send('Input.insertText',{text:'patch@92ng.com'}); await sleep(600);
console.log('val:', await c.eval("document.querySelector('input[placeholder=\"Enter Your Email Address\"]').value"));
await ev('mouseMoved',{x:682,y:473}); await sleep(150);
await ev('mousePressed',{x:682,y:473,button:'left',clickCount:1}); await sleep(100);
await ev('mouseReleased',{x:682,y:473,button:'left',clickCount:1});
await sleep(6000);
console.log('URL:', await c.evalT('location.href', 6000));
console.log('BODY:', await c.evalT("document.body.innerText.split(String.fromCharCode(10)).filter(function(s){return s.trim();}).slice(0,12).join(' | ')", 8000));
reqs.slice(-4).forEach(r => console.log(r));
const s = await c.send('Page.captureScreenshot', {format:'png'}).catch(()=>null);
if(s) writeFileSync('D:/Github/seoadminC/storage/_reg0000/patch_final.png', Buffer.from(s.data,'base64'));
console.log('SHOT ok');
