import { CDP, sleep } from './CDP.mjs';
import fs from 'fs';
const REAL = 'https://letterpad.app/api/auth/callback/email?callbackUrl=https%3A%2F%2Fletterpad.app%2Fregister&token=230a813af2437b08d56f9b48959fcd9e481fea542c1e9a7b1dfed444f43caa39&email=letterpad%4092ng.com';
await fetch('http://127.0.0.1:9224/json/new?about:blank', { method: 'PUT' });
await sleep(400);
const list = await (await fetch('http://127.0.0.1:9224/json/list')).json();
const blank = list.find(t => t.type === 'page' && /about:blank/.test(t.url));
const ws = new WebSocket(blank.webSocketDebuggerUrl);
await new Promise((res, rej) => { ws.onopen = res; ws.onerror = rej; setTimeout(rej, 8000); });
const c = new CDP(ws);
await c.send('Target.activateTarget', { targetId: blank.id });
await c.send('Page.enable');
await c.send('Page.navigate', { url: REAL });
await sleep(7000);
console.log('WHERE:', await c.evalT('location.href', 8000));
console.log('TEXT:', await c.evalT("document.body ? document.body.innerText.split(String.fromCharCode(10)).filter(function(s){return s.trim();}).slice(0,14).join(' | ') : 'nobody'", 8000));
const shot = await c.send('Page.captureScreenshot', { format: 'png' }).catch(() => null);
if (shot) fs.writeFileSync('D:/Github/seoadminC/storage/_reg0000/lp_after_cb.png', Buffer.from(shot.data, 'base64'));
console.log('cookies:', JSON.stringify(await c.send('Network.getCookies')).slice(0, 400));
