import { CDP, sleep } from './CDP.mjs';
import fs from 'fs';
const log = (s) => fs.writeSync(1, s + '\n');
let tab = [...(await (await fetch('http://127.0.0.1:9224/json/list')).json())].find(t => t.type === 'page' && t.url.includes('youslade'));
const ws = new WebSocket(tab.webSocketDebuggerUrl);
await new Promise((res, rej) => { ws.onopen = res; ws.onerror = rej; setTimeout(() => rej(new Error('ws超时')), 8000); });
const c = new CDP(ws);
await c.send('Target.activateTarget', { targetId: tab.id });
await c.send('Page.enable');
const sleepMs = (ms) => new Promise(r => setTimeout(r, ms));
await c.send('Page.navigate', { url: 'https://youslade.com/leoxm26v' });
await sleepMs(8000);
const cur = await c.evalT('location.href', 6000);
log('URL: ' + cur);
const js = "(() => { if (!document.body) return 'NOBODY'; return 'HIT=' + document.body.innerText.includes('bakery fan') + ' | hasPostLinks=' + (document.querySelectorAll('a[href*=status],a[href*=post]').length); })()";
log(await c.evalT(js, 10000));
const shot = await c.send('Page.captureScreenshot', { format: 'png' });
fs.writeFileSync('D:/Github/seoadminC/storage/_reg0000_ys_prof.png', Buffer.from(shot.data, 'base64'));
log('SHOT DONE');
ws.close(); process.exit(0);
