import { CDP, sleep } from './CDP.mjs';
import { writeFileSync } from 'fs';
const tab = [...(await (await fetch('http://127.0.0.1:9224/json/list')).json())].find(t => t.type === 'page' && /dreamwidth\.org\/create/.test(t.url));
const ws = new WebSocket(tab.webSocketDebuggerUrl);
await new Promise((res, rej) => { ws.onopen = res; ws.onerror = rej; });
const c = new CDP(ws);
await c.send('Page.enable');
const ev = (t, p) => c.send('Input.dispatchMouseEvent', { type: t, ...p });
await ev('mouseMoved', { x: 674, y: 767 }); await sleep(150);
await ev('mousePressed', { x: 674, y: 767, button: 'left', clickCount: 1 }); await sleep(90);
await ev('mouseReleased', { x: 674, y: 767, button: 'left', clickCount: 1 });
await sleep(4000);
const s = await c.send('Page.captureScreenshot', { format: 'png' }).catch(() => null);
if (s) writeFileSync('D:/Github/seoadminC/storage/_reg0000/dw_verify.png', Buffer.from(s.data, 'base64'));
console.log('SHOT ok');
process.exit(0);
