import { CDP, sleep } from './CDP.mjs';
import fs from 'fs';
const list = await (await fetch('http://127.0.0.1:9224/json/list')).json();
const tab = list.find(t => t.type === 'page' && /letterpad/.test(t.url));
const ws = new WebSocket(tab.webSocketDebuggerUrl);
await new Promise((res, rej) => { ws.onopen = res; ws.onerror = rej; setTimeout(rej, 8000); });
const c = new CDP(ws);
await c.send('Target.activateTarget', { targetId: tab.id });
await c.send('Page.enable');
await c.send('Page.navigate', { url: 'https://letterpad.app/register' });
await sleep(6000);
console.log('WHERE:', await c.evalT('location.href', 8000));
console.log('TEXT:', await c.evalT("document.body ? document.body.innerText.split(String.fromCharCode(10)).filter(function(s){return s.trim();}).slice(0,20).join(' | ') : 'nobody'", 8000));
const shot = await c.send('Page.captureScreenshot', { format: 'png' }).catch(() => null);
if (shot) fs.writeFileSync('D:/Github/seoadminC/storage/_reg0000/lp_reg3.png', Buffer.from(shot.data, 'base64'));
console.log('SHOT ok');
