import { CDP, sleep } from './CDP.mjs';
import { writeFileSync } from 'fs';
let tab = [...(await (await fetch('http://127.0.0.1:9224/json/list')).json())].find(t => t.type === 'page' && t.url.includes('strikingly.com'));
const ws = new WebSocket(tab.webSocketDebuggerUrl);
await new Promise((res, rej) => { ws.onopen = res; ws.onerror = rej; });
const c = new CDP(ws);
await c.send('Page.enable');
const shot = await c.send('Page.captureScreenshot', { format: 'png', clip: { x: 570, y: 735, width: 410, height: 580, scale: 2.2 } });
writeFileSync('D:/Github/seoadminC/storage/_stri-challenge.png', Buffer.from(shot.data, 'base64'));
console.log('challenge shot saved');
process.exit(0);
