import { CDP, sleep } from './CDP.mjs';
import fs from 'fs';
const log = (s) => fs.writeSync(1, s + '\n');
let tab = [...(await (await fetch('http://127.0.0.1:9224/json/list')).json())].find(t => t.type === 'page' && t.url.includes('creatorlink'));
const ws = new WebSocket(tab.webSocketDebuggerUrl);
await new Promise((res, rej) => { ws.onopen = res; ws.onerror = rej; setTimeout(() => rej(new Error('ws超时')), 8000); });
const c = new CDP(ws);
await c.send('Page.enable');
await sleep(10000);
const cur = await c.evalT('location.href', 6000);
log('CUR: ' + cur);
const body = await c.evalT(`(() => {
  const b = document.body;
  if (!b) return 'NOBODY';
  const btns = [...document.querySelectorAll('a,button,[onclick],[class*=btn]')].map(e => (e.innerText||'').replace(/\s+/g,' ').trim()).filter(t => t && t.length < 40);
  return 'BODYTXT: ' + b.innerText.replace(/\n+/g,' | ').slice(0,600) + ' ||| BTNS: ' + [...new Set(btns)].slice(0,25).join(', ');
})()`, 10000);
log(body);
const shot = await c.send('Page.captureScreenshot', { format: 'png' });
fs.writeFileSync('D:/Github/seoadminC/storage/_reg0000_cl_cfg.png', Buffer.from(shot.data, 'base64'));
log('SHOT DONE');
