import { CDP, sleep } from './CDP.mjs';
import fs from 'fs';
const log = (s) => fs.writeSync(1, s + '\n');
let tab = [...(await (await fetch('http://127.0.0.1:9224/json/list')).json())].find(t => t.type === 'page' && t.url.includes('youslade'));
const ws = new WebSocket(tab.webSocketDebuggerUrl);
await new Promise((res, rej) => { ws.onopen = res; ws.onerror = rej; setTimeout(() => rej(new Error('ws超时')), 8000); });
const c = new CDP(ws);
await c.send('Target.activateTarget', { targetId: tab.id });
await c.send('Page.enable');
const sleepMs = (ms) => new Promise(r => setTimeout(r, ms));
const js = "(() => { const t=document.querySelector('textarea[name=postText]'); if(!t) return 'NOTA'; t.scrollIntoView({block:'center'}); t.focus(); const r=t.getBoundingClientRect(); return Math.round(r.x+r.width/2)+','+Math.round(r.y+r.height/2); })()";
const pos = await c.evalT(js, 8000);
log('TA: ' + pos);
if (pos === 'NOTA') { ws.close(); process.exit(2); }
const [x, y] = pos.split(',').map(Number);
await c.send('Input.dispatchMouseEvent', { type: 'mouseMoved', x, y });
await c.send('Input.dispatchMouseEvent', { type: 'mousePressed', x, y, button: 'left', clickCount: 1 });
await c.send('Input.dispatchMouseEvent', { type: 'mouseReleased', x, y, button: 'left', clickCount: 1 });
await sleepMs(800);
await c.send('Input.insertText', { text: "I keep coming back to the same small pleasure: watching the street wake up. Around seven the bakery fan kicks on, the first bus sighs at the corner, and the man with the checkered cap walks his dog past the launderette like he is inspecting it. None of it is remarkable, which is exactly why it works. On slow mornings I make tea, stand by the window, and let the street do its comedy routine. The dog always barks at the same lamppost. The lamppost, to its credit, has never once reacted. I used to fill mornings with news and notifications, and it turns out that was a terrible trade. The street asks nothing of me. It just performs, rain or shine, and somehow the day starts lighter for having watched it. Find your window. Find your seven a.m. Everything else can wait ten minutes." });
await sleepMs(800);
const len = await c.evalT("(() => { const t=document.querySelector('textarea[name=postText]'); return t ? t.value.length : 'NO'; })()", 8000);
log('LEN: ' + len);
const pub = await c.evalT("(() => { const b=document.querySelector('#publisher-button'); if(!b) return 'NOBTN'; const r=b.getBoundingClientRect(); return Math.round(r.x+r.width/2)+','+Math.round(r.y+r.height/2); })()", 8000);
log('PUB: ' + pub);
const [px, py] = pub.split(',').map(Number);
await c.send('Input.dispatchMouseEvent', { type: 'mouseMoved', x: px, y: py });
await c.send('Input.dispatchMouseEvent', { type: 'mousePressed', x: px, y: py, button: 'left', clickCount: 1 });
await c.send('Input.dispatchMouseEvent', { type: 'mouseReleased', x: px, y: py, button: 'left', clickCount: 1 });
await sleepMs(5000);
const shot = await c.send('Page.captureScreenshot', { format: 'png' });
fs.writeFileSync('D:/Github/seoadminC/storage/_reg0000_ys_pub.png', Buffer.from(shot.data, 'base64'));
log('SHOT DONE');
ws.close(); process.exit(0);
