import { CDP, sleep } from './CDP.mjs';
import fs from 'fs';
await fetch('http://127.0.0.1:9224/json/new?about:blank', { method: 'PUT' });
await sleep(300);
const list = await (await fetch('http://127.0.0.1:9224/json/list')).json();
const tab = list.filter(t => t.type === 'page' && /about:blank/.test(t.url)).pop();
const ws = new WebSocket(tab.webSocketDebuggerUrl);
await new Promise((res, rej) => { ws.onopen = res; ws.onerror = rej; setTimeout(rej, 8000); });
const c = new CDP(ws);
await c.send('Target.activateTarget', { targetId: tab.id });
await c.send('Page.enable');
await c.send('Page.navigate', { url: 'https://postach.io/register/create' });
await sleep(8000);
console.log('URL:', await c.evalT('location.href', 8000));
console.log('TEXT:', await c.evalT("document.body ? document.body.innerText.split(String.fromCharCode(10)).filter(function(s){return s.trim();}).slice(0,20).join(' | ') : 'nobody'", 10000));
console.log('FIELDS:', await c.evalT("JSON.stringify([...document.querySelectorAll('input,select,textarea,button,[role=button],iframe')].map(function(e){return (e.tagName==='IFRAME'?'IF:'+e.src.slice(0,60):e.tagName+':'+(e.name||e.id||e.type||'')+(e.placeholder?':ph='+e.placeholder.slice(0,25):''));}).slice(0,25))", 8000));
const shot = await c.send('Page.captureScreenshot', { format: 'png' }).catch(() => null);
if (shot) fs.writeFileSync('D:/Github/seoadminC/storage/_reg0000/postach_open.png', Buffer.from(shot.data, 'base64'));
console.log('SHOT ok');
