import { CDP, sleep } from './CDP.mjs';
import fs from 'fs';
const log = (s) => fs.writeSync(1, s + '\n');
let tab = [...(await (await fetch('http://127.0.0.1:9224/json/list')).json())].find(t => t.type === 'page' && t.url.includes('youslade'));
const ws = new WebSocket(tab.webSocketDebuggerUrl);
await new Promise((res, rej) => { ws.onopen = res; ws.onerror = rej; setTimeout(() => rej(new Error('ws超时')), 8000); });
const c = new CDP(ws);
await c.send('Target.activateTarget', { targetId: tab.id });
await c.send('Page.enable');
await sleep(6000);
const cur = await c.evalT('location.href', 6000);
log('URL: ' + cur);
const js = "(() => { if (!document.body) return 'NOBODY'; const hit = document.body.innerText.includes('bakery fan'); return 'HIT=' + hit; })()";
log(await c.evalT(js, 10000));
const link = await c.evalT("(() => { if (!document.body) return 'NOBODY'; for (const a of document.querySelectorAll('a[href]')) { if (/leoxm26v/.test(a.href) && a.href.split('/').length > 4) return a.href; } return 'NOLINK'; })()", 8000);
log('LINK: ' + link);
const shot = await c.send('Page.captureScreenshot', { format: 'png' });
fs.writeFileSync('D:/Github/seoadminC/storage/_reg0000_ys_feed.png', Buffer.from(shot.data, 'base64'));
log('SHOT DONE');
ws.close(); process.exit(0);
