import { CDP, sleep } from './CDP.mjs';
import { writeFileSync } from 'fs';
const tab = [...(await (await fetch('http://127.0.0.1:9224/json/list')).json())].find(t => t.type === 'page' && t.url.includes('postach.io/register'));
const ws = new WebSocket(tab.webSocketDebuggerUrl);
await new Promise((res, rej) => { ws.onopen = res; ws.onerror = rej; });
const c = new CDP(ws);
await c.send('Page.enable'); await c.send('Network.enable');
const reqs = [];
c.on(m => { if (m.method === 'Network.requestWillBeSent') reqs.push({u: m.params.request.url.slice(0,120), mth: m.params.request.method}); });
const ev = (t, p) => c.send('Input.dispatchMouseEvent', { type: t, ...p });
const x = 890, y = 659;
await ev('mouseMoved', {x, y}); await sleep(200);
await ev('mousePressed', {x, y, button:'left', clickCount:1}); await sleep(120);
await ev('mouseReleased', {x, y, button:'left', clickCount:1});
await sleep(6000);
console.log('BODY:', await c.evalT("document.body.innerText.split(String.fromCharCode(10)).filter(function(s){return s.trim();}).slice(0,8).join(' | ')", 6000));
console.log('URL:', await c.evalT('location.href', 6000));
reqs.filter(r => !/\.(png|css|js|woff|jpg|gif)/.test(r.u)).slice(-6).forEach(r => console.log('REQ:', r.mth, r.u));
const shot = await c.send('Page.captureScreenshot', {format:'png'}).catch(()=>null);
if(shot) writeFileSync('D:/Github/seoadminC/storage/_reg0000/postach_verify.png', Buffer.from(shot.data,'base64'));
console.log('SHOT ok');
