import { CDP, sleep } from './CDP.mjs';
import { writeFileSync } from 'fs';
const tab = [...(await (await fetch('http://127.0.0.1:9224/json/list')).json())].find(t => t.type === 'page' && /dreamwidth\.org\/create/.test(t.url));
const ws = new WebSocket(tab.webSocketDebuggerUrl);
await new Promise((res, rej) => { ws.onopen = res; ws.onerror = rej; });
const c = new CDP(ws);
await c.send('Page.enable');
const ev = (t, p) => c.send('Input.dispatchMouseEvent', { type: t, ...p });
await fetch(`http://127.0.0.1:9224/json/activate/${tab.id}`).catch(() => {});
await sleep(400);
// 滚回 Create Account 按钮
await c.evalT(`document.querySelector('input[value*="Create Account"]').scrollIntoView({block:'center'})`);
await sleep(800);
const pos = await c.evalT(`JSON.stringify((function(){var b=document.querySelector('input[value*="Create Account"]'); var r=b.getBoundingClientRect(); return {x:Math.round(r.x+r.width/2), y:Math.round(r.y+r.height/2)};})())`, 6000);
console.log('BTN:', pos);
const P = JSON.parse(pos);
await ev('mouseMoved', { x: P.x, y: P.y }); await sleep(150);
await ev('mousePressed', { x: P.x, y: P.y, button: 'left', clickCount: 1 }); await sleep(90);
await ev('mouseReleased', { x: P.x, y: P.y, button: 'left', clickCount: 1 });
await sleep(5000);
console.log('URL:', await c.evalT('location.href', 8000));
console.log('BODY:', await c.evalT("document.body.innerText.split(String.fromCharCode(10)).filter(function(s){return s.trim();}).slice(0,12).join(' | ').slice(0,350)", 8000));
const s = await c.send('Page.captureScreenshot', { format: 'png' }).catch(() => null);
if (s) writeFileSync('D:/Github/seoadminC/storage/_reg0000/dw_submitted.png', Buffer.from(s.data, 'base64'));
console.log('SHOT ok');
process.exit(0);
