import { CDP, sleep } from './CDP.mjs';
import { writeFileSync } from 'fs';
const tab = [...(await (await fetch('http://127.0.0.1:9224/json/list')).json())].find(t => t.type === 'page' && /writeupcafe\.com/.test(t.url));
const ws = new WebSocket(tab.webSocketDebuggerUrl);
await new Promise((res, rej) => { ws.onopen = res; ws.onerror = rej; });
const c = new CDP(ws);
await c.send('Page.enable');
const ev = (t, p) => c.send('Input.dispatchMouseEvent', { type: t, ...p });
// token 还在? 刷新 token 后直接提交
console.log('TOKEN_FILL:', await c.evalT(`(async function(){try{var t=await grecaptcha.enterprise.execute('6Lfj9KQsAAAAAOfmTJ5-QQz4OEG7tTps49vot8p1'); var inp=document.querySelector('#rcToken'); if(inp) inp.value=t; return 'ok_len='+t.length;}catch(e){return 'ERR '+e.message;}})()`, 15000));
const pos = await c.evalT(`(function(){var b=document.querySelector('#regBtn'); if(!b) return 'NO'; b.scrollIntoView({block:'center'}); var r=b.getBoundingClientRect(); return [Math.round(r.x+r.width/2), Math.round(r.y+r.height/2)].join('|');})()`, 8000);
const [x, y] = pos.split('|').map(Number);
await sleep(300);
await ev('mouseMoved', { x, y }); await sleep(150);
await ev('mousePressed', { x, y, button: 'left', clickCount: 1 }); await sleep(90);
await ev('mouseReleased', { x, y, button: 'left', clickCount: 1 });
await sleep(7000);
console.log('URL:', await c.evalT('location.href', 8000));
console.log('BODY:', await c.evalT(`document.body.innerText.split(String.fromCharCode(10)).filter(function(s){return s.trim();}).slice(0,12).join(' | ').slice(0,350)`, 8000));
const s = await c.send('Page.captureScreenshot', { format: 'png' }).catch(() => null);
if (s) writeFileSync('D:/Github/seoadminC/storage/_reg0000/wu_submitted2.png', Buffer.from(s.data, 'base64'));
console.log('SHOT ok');
process.exit(0);
