import { CDP, sleep } from './CDP.mjs';
import fs from 'fs';
const list = await (await fetch('http://127.0.0.1:9224/json/list')).json();
const tab = list.find(t => (t.url || '').includes('poordirectory') && t.type === 'page');
const c = new CDP(new WebSocket(tab.webSocketDebuggerUrl));
await new Promise(r => c.ws.addEventListener('open', r));
await c.send('Page.enable');
const b = await c.eval(`(() => { const s=document.querySelector('input[name=submit]'); if(!s) return 'NO-SUBMIT'; s.scrollIntoView({block:'center'}); const r=s.getBoundingClientRect(); return JSON.stringify({x: Math.round(r.x+r.width/2), y: Math.round(r.y+r.height/2), v: s.value}); })()`);
console.log('SUBMIT BTN:', b);
const B = JSON.parse(b);
await c.send('Input.dispatchMouseEvent', { type: 'mouseMoved', x: B.x, y: B.y });
await sleep(150);
await c.send('Input.dispatchMouseEvent', { type: 'mousePressed', x: B.x, y: B.y, button: 'left', clickCount: 1 });
await sleep(100);
await c.send('Input.dispatchMouseEvent', { type: 'mouseReleased', x: B.x, y: B.y, button: 'left', clickCount: 1 });
await sleep(9000);
const r = await c.eval(`(() => { const t = document.body.innerText.toLowerCase(); const keys = ['submitted','awaiting','approval','thank','error','required','already','violation']; const hit = keys.find(k => t.includes(k)); return JSON.stringify({url: location.href.slice(0,90), hit, msg: hit ? t.slice(Math.max(0,t.indexOf(hit)-60), t.indexOf(hit)+120).slice(0,200) : t.slice(0,140)}); })()`);
console.log('AFTER SUBMIT:', r);
const sh = await c.send('Page.captureScreenshot', { format: 'png' });
await fs.promises.writeFile('D:/Github/seoadminC/storage/_w12_pd_final.png', Buffer.from(sh.data, 'base64'));
