import { CDP, sleep } from './CDP.mjs';
import fs from 'fs';
const list = await (await fetch('http://127.0.0.1:9224/json/list')).json();
const tab = list.find(x => x.id === process.argv[2]);
const cdp = new CDP(new WebSocket(tab.webSocketDebuggerUrl));
await new Promise((res, rej) => { cdp.ws.addEventListener('open', res); setTimeout(() => rej(new Error('ws-timeout')), 10000); });
await cdp.send('Page.enable');
await sleep(9000);
const r = await cdp.eval("(() => JSON.stringify({url: location.href.slice(0,90), title: document.title.slice(0,45), head: document.body.innerText.slice(0,300)}))()");
console.log('LP2:', r.slice(0, 400));
const shot = await cdp.send('Page.captureScreenshot', { format: 'png' });
await fs.promises.writeFile('D:/Github/backlink_skills/storage/_w1200_lp_posts.png', Buffer.from(shot.data, 'base64'));
