import { CDP, sleep } from './CDP.mjs';
const [DOM] = process.argv.slice(2);
const tabs = await (await fetch('http://127.0.0.1:9224/json/list')).json();
const tab = tabs.find(t => (t.url || '').includes(DOM) && t.type === 'page');
const ws = new WebSocket(tab.webSocketDebuggerUrl);
await new Promise(r => ws.onopen = r);
const cdp = new CDP(ws);
const st = await cdp.eval(`(() => { const b=document.querySelector('.g-recaptcha'); if(!b) return 'NOBOX'; b.scrollIntoView({block:'center'}); const r=b.getBoundingClientRect(); return 'BOX y='+Math.round(r.y); })()`);
console.log(st);
ws.close();
