import { CDP, sleep } from './CDP.mjs';
import fs from 'fs';
const [,, domain, draftFile] = process.argv;
const draft = JSON.parse(fs.readFileSync(draftFile, 'utf8'));
const base = 'http://127.0.0.1:9224';
let tabs = await (await fetch(base+'/json/list')).json();
let tab = tabs.find(t => t.type==='page' && t.url.includes(domain));
const ws = new WebSocket(tab.webSocketDebuggerUrl);
await new Promise((res,rej)=>{ws.onopen=res;ws.onerror=rej;});
const c = new CDP(ws);
await c.send('Page.enable'); await c.send('Runtime.enable');
const clickXY = async (x,y) => { await c.send('Input.dispatchMouseEvent',{type:'mouseMoved',x,y}); await c.send('Input.dispatchMouseEvent',{type:'mousePressed',x,y,button:'left',clickCount:1}); await c.send('Input.dispatchMouseEvent',{type:'mouseReleased',x,y,button:'left',clickCount:1}); };
await c.send('Page.navigate',{url:'https://'+domain+'/new-post'});
await sleep(9000);
// 快填: JS原生setter + click
await c.eval(`(function(){var t=document.querySelector('#title');t.focus();})()`);
await c.send('Input.insertText',{text:draft.title});
await sleep(300);
await c.eval(`(function(){var b=[...document.querySelectorAll('button,a,div[role=tab]')].find(function(x){return x.offsetParent&&(x.innerText||'').trim()==='Text'});if(b)b.click();})()`);
await sleep(700);
await c.eval(`(function(){document.querySelector('#content').focus();})()`);
await c.send('Input.insertText',{text:draft.body});
await sleep(500);
console.log('filled:', await c.eval(`document.querySelector('#title').value.length+' / '+document.querySelector('#content').value.length`));
const r = await c.eval(`(function(){var b=[...document.querySelectorAll('button,input[type=submit],a')].find(function(x){return x.offsetParent&&(x.innerText||x.value||'').trim().indexOf('Publish')===0});if(!b)return 'NO';b.scrollIntoView({block:'center'});var q=b.getBoundingClientRect();return JSON.stringify({x:Math.round(q.x+q.width/2),y:Math.round(q.y+q.height/2),id:b.id,form:b.form?b.form.id:null});})()`);
console.log('pubbtn:', r);
const pp=JSON.parse(r); await clickXY(pp.x,pp.y);
await sleep(5000);
const st = await c.evalT("(function(){var N=String.fromCharCode(10);return 'HREF='+location.href+'<<T>>'+document.body.innerText.slice(0,600).split(N).join('~');})()", 8000);
console.log(st);
const shot = await c.send('Page.captureScreenshot',{format:'png'});
fs.writeFileSync('D:/Github/seoadminC/storage/_win2000_pubshot.png', Buffer.from(shot.data,'base64'));
process.exit(0);
